name: Build and Test
on:
  push:
    branches:
    - 'master'
jobs:
  build-node:
    name: Build Node
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [ 18, 20, 21 ]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v4

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-

    - name: Install system dependencies
      run: "apt-get update && apt-get install -y wget gnupg gconf-service\\

        \  libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1\\

        \  libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0\\

        \  libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6\\

        \  libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1\\

        \  libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6\\

        \  libgbm-dev ca-certificates fonts-liberation \\

        \  ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-noto-cjk fonts-arphic-uming\\

        \  libappindicator1 libnss3 lsb-release xdg-utils

        \  "
    - name: Display Node version
      run: node --version

    - name: Install puppeteer
      run: npm install -g puppeteer@24.7.1

    - name: Install chrome-headless-shell
      run: npx @puppeteer/browsers install chrome-headless-shell@stable --verbose

    - name: Install dependencies
      run: npm i --verbose

    - name: Run tests
      run: npm run test
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        NODE_ENV: test

    - name: Run benchmark
      run: npm run benchmark
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        NODE_ENV: test

  build-docker:
    name: Build and Push Docker
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_TOKEN }}'

    - name: Set tag name based on branch
      id: set_tag
      run: |
        if [[ "${{ github.ref_name }}" == "master" ]]; then
          echo "tags=davilson18/headlessbrowserapi:latest" >> $GITHUB_OUTPUT
        else
          GITHUB_REFNAME=${{ github.ref_name }}
          BRANCH_NAME=${GITHUB_REFNAME//\//_}
          echo "tags=davilson18/headlessbrowserapi:$BRANCH_NAME" >> $GITHUB_OUTPUT
        fi

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.set_tag.outputs.tags }}
        cache-from: type=registry,ref=davilson18/headlessbrowserapi:buildcache
        cache-to: type=registry,ref=davilson18/headlessbrowserapi:buildcache,mode=max
